[tool.poetry]
name = "ephyr-control"
version = "1.0.0"
description = ""
authors = ["Serhii Khalymon <sergiykhalimon@gmail.com>", "Illia Ananich <illia.ananich@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
yarl = "^1.6"
gql = {version = "^2.0", extras = ["requests"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
