name: pre-commit

on: [push]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: |
                  pip install -U pip
                  pip install poetry
                  poetry config virtualenvs.create false --local
                  poetry install --with dev
            - uses: pre-commit/action@v2.0.0
