name: Ephyr Control tests

on: [push]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install --with dev -E subscriber-cli
      - name: Test with pytest
        run: |
          poetry run pytest
